name: movieproject2

channels:
  - conda-forge
  - anaconda
  - defaults
  - pip
dependencies:
  - python=3.12.8
  - pip=24.3.1
  - pandas=2.2.2
  - numpy=1.26.4
  - scipy=1.13.1
  - nibabel=5.3.2
  - nilearn=0.11.1
  - mne=1.7.0
  - pip:
    - pydeface==2.0.2